### ISSUE TITLE
Failed to compile on 5.11.0

### ISSUE THREAD

**Issue by chenk008** [alibaba/diagnose-tools#158]
`fcheck_files` has been renamed to  `files_lookup_fd_rcu`

```
/root/diagnose-tools/SOURCE/module/pub/uprobe.c: In function ‘hook_uprobe’:
/root/diagnose-tools/SOURCE/module/pub/uprobe.c:47:16: error: implicit declaration of function ‘fcheck_files’ [-Werror=implicit-function-declaration]
   47 |         file = fcheck_files(files, fd);
      |                ^~~~~~~~~~~~
/root/diagnose-tools/SOURCE/module/pub/uprobe.c:47:14: warning: assignment to ‘struct file *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   47 |         file = fcheck_files(files, fd);
      |              ^
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:281: /root/diagnose-tools/SOURCE/module/pub/uprobe.o] Error 1
```
